### ISSUE TITLE
Please tell me a collect usage of TsyDMASPI

### ISSUE THREAD

**Issue by Ninagawa123** [hideakitai/TsyDMASPI#1]
Thank you for your great library.
I want to use it with Teensy4.0 as a master and ESP32(with ESP32DMASPI) as a Slave.

First, I tried it with the following script and it worked fine. But this has not used TsyDMASPI yet.
https://github.com/Ninagawa123/test/blob/master/Teensy40_master_ESP32_slave_test_git_ok.ino
https://github.com/Ninagawa123/test/blob/master/esp32_slave_teensy40_master_test_git.ino
Teensy 4.0 sends 1 byte at a time with this script.

ESP32 results https://github.com/Ninagawa123/test/blob/master/esp32_spi_result1.png
and Teensy4.0 https://github.com/Ninagawa123/test/blob/master/teensy_spi_result1.png

Then I tried TsyDMASP with Teensy4.0.(ESP32 used the same script as the first.)
https://github.com/Ninagawa123/test/blob/master/Teensy40_master_ESP32_slave_test_with_TsyDAMSPI_git.ino

ESP32 results  https://github.com/Ninagawa123/test/blob/master/esp32_spi_result2.png
and Teensy4.0 https://github.com/Ninagawa123/test/blob/master/teensy_spi_result2.png

It skipped numbers.
I think it's because I'm using this library incorrectly.

Can you please tell me a collect usage of TsyDMASPI ?

Regards.

**Comment by hideakitai** [comment]
@Ninagawa123 Hi, sorry for the late reply.

First, you don't need to `begin()` every `loop()`. Please do it only once in `setup()`
https://github.com/Ninagawa123/test/blob/8baefa2fa7e6740d8b39fc977dba76d489714ee7/Teensy40_master_ESP32_slave_test_with_TsyDAMSPI_git.ino#L48

This SPI preparation is also done in the `TsyDMASPI.begin()`, so you don't need to call it.
https://github.com/Ninagawa123/test/blob/8baefa2fa7e6740d8b39fc977dba76d489714ee7/Teensy40_master_ESP32_slave_test_with_TsyDAMSPI_git.ino#L19

You don't need to drive the `SS` pin by yourself. It's automatically controlled by `TsyDMASPI`
https://github.com/Ninagawa123/test/blob/8baefa2fa7e6740d8b39fc977dba76d489714ee7/Teensy40_master_ESP32_slave_test_with_TsyDAMSPI_git.ino#L52

If you still have any problems, please let me know.

**Comment by Ninagawa123** [comment]
Thank you for your advice!
I modified it as follows according to your instructions.
Teensy40_master_ESP32_slave_test_with_TsyDAMSPI_git_Fixed1.ino

It worked, but the result is the same as before, the numbers are skipped.

teensy(master) monitoring
teensy_spi_result3.png

esp32(slave) monitoring
esp32_spi_result3.png

By the way, I used it wit breadboard and its cable length is about 10cm.
teensu_esp_breadboard.png

And I changed the SPI mode of Teensy from 0 to 3. It seems that Teensy's SPI_MODE3 matches ESP32's SPI_MODE3. This is because scripts without TsyDAMSPI will work with this setting.  

Can you please teach me what to do next?

**Comment by Ninagawa123** [comment]
I've found that all of the changed TsyDAMSPI's MODEs come out same result.
Everything seems to behave like MODE2...

**Comment by Ninagawa123** [comment]
So, I changed ESP32's MODE to SPI_MODE2, It looks work. It didn't skip numbers.
But, ESP32 is not good at MODE2. It can't receive last 4 bytes.

**Comment by hideakitai** [comment]
@Ninagawa123 Sorry, I've found that the transaction did not reflect the SPI configuration... I've tried to fix it in v0.1.3, but I haven't tested it because I don't have the devices. Could you try it?

**Comment by Ninagawa123** [comment]
We did it!
I tried it and now v0.1.3 with SPI_MODE3 is working properly.
Thank you for your support.

**Comment by hideakitai** [comment]
Good luck!
